name: matrix_gesture_detector
description: A gesture detector mapping translation/rotation/scale gestures to a Matrix4 object.
version: 1.0.0
#homepage:
environment:
  sdk: '>=3.2.3 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_drawing: ^1.0.1



dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
